/* Auto-generated by genmsg_cpp for file /home/test_user/usc-arm-calibration/arm_msgs/srv/FindObject.srv */
#ifndef ARM_MSGS_SERVICE_FINDOBJECT_H
#define ARM_MSGS_SERVICE_FINDOBJECT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"

#include "arm_msgs/Object.h"


#include "arm_msgs/Object.h"

namespace arm_msgs
{
template <class ContainerAllocator>
struct FindObjectRequest_ {
  typedef FindObjectRequest_<ContainerAllocator> Type;

  FindObjectRequest_()
  : name()
  , has_parent_object(false)
  , parent_object()
  {
  }

  FindObjectRequest_(const ContainerAllocator& _alloc)
  : name(_alloc)
  , has_parent_object(false)
  , parent_object(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  name;

  typedef uint8_t _has_parent_object_type;
  uint8_t has_parent_object;

  typedef  ::arm_msgs::Object_<ContainerAllocator>  _parent_object_type;
   ::arm_msgs::Object_<ContainerAllocator>  parent_object;


  typedef boost::shared_ptr< ::arm_msgs::FindObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_msgs::FindObjectRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct FindObjectRequest
typedef  ::arm_msgs::FindObjectRequest_<std::allocator<void> > FindObjectRequest;

typedef boost::shared_ptr< ::arm_msgs::FindObjectRequest> FindObjectRequestPtr;
typedef boost::shared_ptr< ::arm_msgs::FindObjectRequest const> FindObjectRequestConstPtr;


template <class ContainerAllocator>
struct FindObjectResponse_ {
  typedef FindObjectResponse_<ContainerAllocator> Type;

  FindObjectResponse_()
  : found(false)
  , object()
  {
  }

  FindObjectResponse_(const ContainerAllocator& _alloc)
  : found(false)
  , object(_alloc)
  {
  }

  typedef uint8_t _found_type;
  uint8_t found;

  typedef  ::arm_msgs::Object_<ContainerAllocator>  _object_type;
   ::arm_msgs::Object_<ContainerAllocator>  object;


  typedef boost::shared_ptr< ::arm_msgs::FindObjectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_msgs::FindObjectResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct FindObjectResponse
typedef  ::arm_msgs::FindObjectResponse_<std::allocator<void> > FindObjectResponse;

typedef boost::shared_ptr< ::arm_msgs::FindObjectResponse> FindObjectResponsePtr;
typedef boost::shared_ptr< ::arm_msgs::FindObjectResponse const> FindObjectResponseConstPtr;

struct FindObject
{

typedef FindObjectRequest Request;
typedef FindObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct FindObject
} // namespace arm_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::arm_msgs::FindObjectRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::arm_msgs::FindObjectRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::arm_msgs::FindObjectRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a3969451e27ff9f1937b0ecc11ee7fa3";
  }

  static const char* value(const  ::arm_msgs::FindObjectRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa3969451e27ff9f1ULL;
  static const uint64_t static_value2 = 0x937b0ecc11ee7fa3ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_msgs::FindObjectRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arm_msgs/FindObjectRequest";
  }

  static const char* value(const  ::arm_msgs::FindObjectRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arm_msgs::FindObjectRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
string name\n\
\n\
\n\
\n\
bool has_parent_object\n\
arm_msgs/Object parent_object\n\
\n\
================================================================================\n\
MSG: arm_msgs/Object\n\
string name\n\
string ORANGE_PAPER=orange_paper\n\
string BALL=ball\n\
string ROCK=rock\n\
string CANTEEN=canteen\n\
string CANTEEN_STANDING=canteen_standing\n\
string CANTEEN_LYING=canteen_lying\n\
string PVC_PIPE_BIG=pipe\n\
string PVC_PIPE_BIG_STANDING=pipe_standing\n\
string PVC_PIPE_BIG_LYING=pipe_lying\n\
string STAPLER=stapler\n\
string FLASHLIGHT=flashlight\n\
string FLASHLIGHT_UP=flashlight_up\n\
string DOOR=door\n\
string DOOR_UNLOCK=door_unlock\n\
string BOTTLE=bottle\n\
string MAGLITE=maglite\n\
string MAGLITE_UP=maglite_up\n\
string MAGLITE_DOWN=maglite_down\n\
string MAGLITE_LYING=maglite_lying\n\
string RADIO=radio\n\
string HANDSET=handset\n\
string HANDSET_DOWN=handset_down\n\
string CRADLE=cradle\n\
string CRADLE_FLAT=cradle_flat\n\
string CRADLE_VERTICAL=cradle_vertical\n\
string SCREWDRIVER=screwdriver\n\
string DRILL=drill\n\
string DRILL_UPRIGHT=drill_upright\n\
string DRILL_BLOCK=drill_block\n\
string DRILL_BLOCK_LYING=drill_block_lying\n\
string DRILL_BLOCK_STANDING=drill_block_standing\n\
string RED_DOT=red_dot\n\
string SHOVEL=shovel\n\
string SHOVEL_FLAT=shovel_flat\n\
string SHOVEL_ONEDGE=shovel_onedge\n\
string HAMMER=hammer\n\
string HAMMER_DOWN=hammer_down\n\
string HAMMER_LYING=hammer_lying\n\
string HAMMER_UP=hammer_up\n\
string HAMMER_ONEDGE=hammer_onedge\n\
string FLOODLIGHT=floodlight\n\
string FLOODLIGHT_SIDE=floodlight_side\n\
string FLOODLIGHT_DOWN=floodlight_down\n\
string PELICAN=pelican\n\
string PELICAN_HANDLE_UP=pelican_handle_up\n\
string PELICAN_LABEL_UP=pelican_label_up\n\
string PELICAN_LABEL_DOWN=pelican_label_down\n\
string PELICAN_LEFT_EDGE_DOWN=pelican_left_edge_down\n\
string PELICAN_RIGHT_EDGE_DOWN=pelican_right_edge_down\n\
geometry_msgs/PoseWithCovarianceStamped pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseWithCovarianceStamped\n\
# This expresses an estimated pose with a reference coordinate frame and timestamp\n\
\n\
Header header\n\
PoseWithCovariance pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseWithCovariance\n\
# This represents a pose in free space with uncertainty.\n\
\n\
Pose pose\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::arm_msgs::FindObjectRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::arm_msgs::FindObjectResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::arm_msgs::FindObjectResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::arm_msgs::FindObjectResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e516bb97c90b8e16da880257a0451e09";
  }

  static const char* value(const  ::arm_msgs::FindObjectResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe516bb97c90b8e16ULL;
  static const uint64_t static_value2 = 0xda880257a0451e09ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_msgs::FindObjectResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arm_msgs/FindObjectResponse";
  }

  static const char* value(const  ::arm_msgs::FindObjectResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arm_msgs::FindObjectResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool found\n\
arm_msgs/Object object\n\
\n\
\n\
================================================================================\n\
MSG: arm_msgs/Object\n\
string name\n\
string ORANGE_PAPER=orange_paper\n\
string BALL=ball\n\
string ROCK=rock\n\
string CANTEEN=canteen\n\
string CANTEEN_STANDING=canteen_standing\n\
string CANTEEN_LYING=canteen_lying\n\
string PVC_PIPE_BIG=pipe\n\
string PVC_PIPE_BIG_STANDING=pipe_standing\n\
string PVC_PIPE_BIG_LYING=pipe_lying\n\
string STAPLER=stapler\n\
string FLASHLIGHT=flashlight\n\
string FLASHLIGHT_UP=flashlight_up\n\
string DOOR=door\n\
string DOOR_UNLOCK=door_unlock\n\
string BOTTLE=bottle\n\
string MAGLITE=maglite\n\
string MAGLITE_UP=maglite_up\n\
string MAGLITE_DOWN=maglite_down\n\
string MAGLITE_LYING=maglite_lying\n\
string RADIO=radio\n\
string HANDSET=handset\n\
string HANDSET_DOWN=handset_down\n\
string CRADLE=cradle\n\
string CRADLE_FLAT=cradle_flat\n\
string CRADLE_VERTICAL=cradle_vertical\n\
string SCREWDRIVER=screwdriver\n\
string DRILL=drill\n\
string DRILL_UPRIGHT=drill_upright\n\
string DRILL_BLOCK=drill_block\n\
string DRILL_BLOCK_LYING=drill_block_lying\n\
string DRILL_BLOCK_STANDING=drill_block_standing\n\
string RED_DOT=red_dot\n\
string SHOVEL=shovel\n\
string SHOVEL_FLAT=shovel_flat\n\
string SHOVEL_ONEDGE=shovel_onedge\n\
string HAMMER=hammer\n\
string HAMMER_DOWN=hammer_down\n\
string HAMMER_LYING=hammer_lying\n\
string HAMMER_UP=hammer_up\n\
string HAMMER_ONEDGE=hammer_onedge\n\
string FLOODLIGHT=floodlight\n\
string FLOODLIGHT_SIDE=floodlight_side\n\
string FLOODLIGHT_DOWN=floodlight_down\n\
string PELICAN=pelican\n\
string PELICAN_HANDLE_UP=pelican_handle_up\n\
string PELICAN_LABEL_UP=pelican_label_up\n\
string PELICAN_LABEL_DOWN=pelican_label_down\n\
string PELICAN_LEFT_EDGE_DOWN=pelican_left_edge_down\n\
string PELICAN_RIGHT_EDGE_DOWN=pelican_right_edge_down\n\
geometry_msgs/PoseWithCovarianceStamped pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseWithCovarianceStamped\n\
# This expresses an estimated pose with a reference coordinate frame and timestamp\n\
\n\
Header header\n\
PoseWithCovariance pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseWithCovariance\n\
# This represents a pose in free space with uncertainty.\n\
\n\
Pose pose\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::arm_msgs::FindObjectResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arm_msgs::FindObjectRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.name);
    stream.next(m.has_parent_object);
    stream.next(m.parent_object);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct FindObjectRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arm_msgs::FindObjectResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.found);
    stream.next(m.object);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct FindObjectResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<arm_msgs::FindObject> {
  static const char* value() 
  {
    return "0e43fcf0548937f45b7976a4586a628c";
  }

  static const char* value(const arm_msgs::FindObject&) { return value(); } 
};

template<>
struct DataType<arm_msgs::FindObject> {
  static const char* value() 
  {
    return "arm_msgs/FindObject";
  }

  static const char* value(const arm_msgs::FindObject&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<arm_msgs::FindObjectRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0e43fcf0548937f45b7976a4586a628c";
  }

  static const char* value(const arm_msgs::FindObjectRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<arm_msgs::FindObjectRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arm_msgs/FindObject";
  }

  static const char* value(const arm_msgs::FindObjectRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<arm_msgs::FindObjectResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0e43fcf0548937f45b7976a4586a628c";
  }

  static const char* value(const arm_msgs::FindObjectResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<arm_msgs::FindObjectResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arm_msgs/FindObject";
  }

  static const char* value(const arm_msgs::FindObjectResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // ARM_MSGS_SERVICE_FINDOBJECT_H

