; Auto-generated. Do not edit!


(cl:in-package arm_behavior_actions-msg)


;//! \htmlinclude GraspObjectResult.msg.html

(cl:defclass <GraspObjectResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:integer
    :initform 0))
)

(cl:defclass GraspObjectResult (<GraspObjectResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GraspObjectResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GraspObjectResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name arm_behavior_actions-msg:<GraspObjectResult> is deprecated: use arm_behavior_actions-msg:GraspObjectResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <GraspObjectResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader arm_behavior_actions-msg:result-val is deprecated.  Use arm_behavior_actions-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<GraspObjectResult>)))
    "Constants for message type '<GraspObjectResult>"
  '((:FAILED . 0)
    (:SUCCEEDED . 1)
    (:REPOSITION . 2)
    (:RETRY . 3))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'GraspObjectResult)))
    "Constants for message type 'GraspObjectResult"
  '((:FAILED . 0)
    (:SUCCEEDED . 1)
    (:REPOSITION . 2)
    (:RETRY . 3))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GraspObjectResult>) ostream)
  "Serializes a message object of type '<GraspObjectResult>"
  (cl:let* ((signed (cl:slot-value msg 'result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GraspObjectResult>) istream)
  "Deserializes a message object of type '<GraspObjectResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GraspObjectResult>)))
  "Returns string type for a message object of type '<GraspObjectResult>"
  "arm_behavior_actions/GraspObjectResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GraspObjectResult)))
  "Returns string type for a message object of type 'GraspObjectResult"
  "arm_behavior_actions/GraspObjectResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GraspObjectResult>)))
  "Returns md5sum for a message object of type '<GraspObjectResult>"
  "a890a1e47d50b4cafc80981aec016f0a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GraspObjectResult)))
  "Returns md5sum for a message object of type 'GraspObjectResult"
  "a890a1e47d50b4cafc80981aec016f0a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GraspObjectResult>)))
  "Returns full string definition for message of type '<GraspObjectResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 result~%int32 FAILED=0~%int32 SUCCEEDED=1~%int32 REPOSITION=2~%int32 RETRY=3~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GraspObjectResult)))
  "Returns full string definition for message of type 'GraspObjectResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 result~%int32 FAILED=0~%int32 SUCCEEDED=1~%int32 REPOSITION=2~%int32 RETRY=3~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GraspObjectResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GraspObjectResult>))
  "Converts a ROS message object to a list"
  (cl:list 'GraspObjectResult
    (cl:cons ':result (result msg))
))
