; Auto-generated. Do not edit!


(cl:in-package arm_behavior_actions-msg)


;//! \htmlinclude LookAtHandGoal.msg.html

(cl:defclass <LookAtHandGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass LookAtHandGoal (<LookAtHandGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LookAtHandGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LookAtHandGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name arm_behavior_actions-msg:<LookAtHandGoal> is deprecated: use arm_behavior_actions-msg:LookAtHandGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LookAtHandGoal>) ostream)
  "Serializes a message object of type '<LookAtHandGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LookAtHandGoal>) istream)
  "Deserializes a message object of type '<LookAtHandGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LookAtHandGoal>)))
  "Returns string type for a message object of type '<LookAtHandGoal>"
  "arm_behavior_actions/LookAtHandGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LookAtHandGoal)))
  "Returns string type for a message object of type 'LookAtHandGoal"
  "arm_behavior_actions/LookAtHandGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LookAtHandGoal>)))
  "Returns md5sum for a message object of type '<LookAtHandGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LookAtHandGoal)))
  "Returns md5sum for a message object of type 'LookAtHandGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LookAtHandGoal>)))
  "Returns full string definition for message of type '<LookAtHandGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LookAtHandGoal)))
  "Returns full string definition for message of type 'LookAtHandGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LookAtHandGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LookAtHandGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'LookAtHandGoal
))
