; Auto-generated. Do not edit!


(cl:in-package arm_behavior_actions-msg)


;//! \htmlinclude LookAtHandFeedback.msg.html

(cl:defclass <LookAtHandFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass LookAtHandFeedback (<LookAtHandFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LookAtHandFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LookAtHandFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name arm_behavior_actions-msg:<LookAtHandFeedback> is deprecated: use arm_behavior_actions-msg:LookAtHandFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LookAtHandFeedback>) ostream)
  "Serializes a message object of type '<LookAtHandFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LookAtHandFeedback>) istream)
  "Deserializes a message object of type '<LookAtHandFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LookAtHandFeedback>)))
  "Returns string type for a message object of type '<LookAtHandFeedback>"
  "arm_behavior_actions/LookAtHandFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LookAtHandFeedback)))
  "Returns string type for a message object of type 'LookAtHandFeedback"
  "arm_behavior_actions/LookAtHandFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LookAtHandFeedback>)))
  "Returns md5sum for a message object of type '<LookAtHandFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LookAtHandFeedback)))
  "Returns md5sum for a message object of type 'LookAtHandFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LookAtHandFeedback>)))
  "Returns full string definition for message of type '<LookAtHandFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LookAtHandFeedback)))
  "Returns full string definition for message of type 'LookAtHandFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LookAtHandFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LookAtHandFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LookAtHandFeedback
))
