; Auto-generated. Do not edit!


(cl:in-package arm_behavior_actions-msg)


;//! \htmlinclude PreshapeHandGoal.msg.html

(cl:defclass <PreshapeHandGoal> (roslisp-msg-protocol:ros-message)
  ((command
    :reader command
    :initarg :command
    :type cl:integer
    :initform 0))
)

(cl:defclass PreshapeHandGoal (<PreshapeHandGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PreshapeHandGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PreshapeHandGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name arm_behavior_actions-msg:<PreshapeHandGoal> is deprecated: use arm_behavior_actions-msg:PreshapeHandGoal instead.")))

(cl:ensure-generic-function 'command-val :lambda-list '(m))
(cl:defmethod command-val ((m <PreshapeHandGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader arm_behavior_actions-msg:command-val is deprecated.  Use arm_behavior_actions-msg:command instead.")
  (command m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<PreshapeHandGoal>)))
    "Constants for message type '<PreshapeHandGoal>"
  '((:OPEN . 0)
    (:PRESHAPE . 1))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'PreshapeHandGoal)))
    "Constants for message type 'PreshapeHandGoal"
  '((:OPEN . 0)
    (:PRESHAPE . 1))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PreshapeHandGoal>) ostream)
  "Serializes a message object of type '<PreshapeHandGoal>"
  (cl:let* ((signed (cl:slot-value msg 'command)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PreshapeHandGoal>) istream)
  "Deserializes a message object of type '<PreshapeHandGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'command) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PreshapeHandGoal>)))
  "Returns string type for a message object of type '<PreshapeHandGoal>"
  "arm_behavior_actions/PreshapeHandGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PreshapeHandGoal)))
  "Returns string type for a message object of type 'PreshapeHandGoal"
  "arm_behavior_actions/PreshapeHandGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PreshapeHandGoal>)))
  "Returns md5sum for a message object of type '<PreshapeHandGoal>"
  "2798a1a15d637be6b77ea9994350ccd5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PreshapeHandGoal)))
  "Returns md5sum for a message object of type 'PreshapeHandGoal"
  "2798a1a15d637be6b77ea9994350ccd5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PreshapeHandGoal>)))
  "Returns full string definition for message of type '<PreshapeHandGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 command~%int32 OPEN=0~%int32 PRESHAPE=1~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PreshapeHandGoal)))
  "Returns full string definition for message of type 'PreshapeHandGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 command~%int32 OPEN=0~%int32 PRESHAPE=1~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PreshapeHandGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PreshapeHandGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PreshapeHandGoal
    (cl:cons ':command (command msg))
))
