; Auto-generated. Do not edit!


(cl:in-package arm_behavior_actions-msg)


;//! \htmlinclude RepositionObjectResult.msg.html

(cl:defclass <RepositionObjectResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:integer
    :initform 0))
)

(cl:defclass RepositionObjectResult (<RepositionObjectResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RepositionObjectResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RepositionObjectResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name arm_behavior_actions-msg:<RepositionObjectResult> is deprecated: use arm_behavior_actions-msg:RepositionObjectResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <RepositionObjectResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader arm_behavior_actions-msg:result-val is deprecated.  Use arm_behavior_actions-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<RepositionObjectResult>)))
    "Constants for message type '<RepositionObjectResult>"
  '((:FAILED . 0)
    (:SUCCEEDED . 1))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'RepositionObjectResult)))
    "Constants for message type 'RepositionObjectResult"
  '((:FAILED . 0)
    (:SUCCEEDED . 1))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RepositionObjectResult>) ostream)
  "Serializes a message object of type '<RepositionObjectResult>"
  (cl:let* ((signed (cl:slot-value msg 'result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RepositionObjectResult>) istream)
  "Deserializes a message object of type '<RepositionObjectResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RepositionObjectResult>)))
  "Returns string type for a message object of type '<RepositionObjectResult>"
  "arm_behavior_actions/RepositionObjectResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RepositionObjectResult)))
  "Returns string type for a message object of type 'RepositionObjectResult"
  "arm_behavior_actions/RepositionObjectResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RepositionObjectResult>)))
  "Returns md5sum for a message object of type '<RepositionObjectResult>"
  "b07fa3ecc4713f4025214b4258afb809")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RepositionObjectResult)))
  "Returns md5sum for a message object of type 'RepositionObjectResult"
  "b07fa3ecc4713f4025214b4258afb809")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RepositionObjectResult>)))
  "Returns full string definition for message of type '<RepositionObjectResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 result~%int32 FAILED=0~%int32 SUCCEEDED=1~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RepositionObjectResult)))
  "Returns full string definition for message of type 'RepositionObjectResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int32 result~%int32 FAILED=0~%int32 SUCCEEDED=1~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RepositionObjectResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RepositionObjectResult>))
  "Converts a ROS message object to a list"
  (cl:list 'RepositionObjectResult
    (cl:cons ':result (result msg))
))
