; Auto-generated. Do not edit!


(cl:in-package arm_behavior_actions-msg)


;//! \htmlinclude ScanForObjectGoal.msg.html

(cl:defclass <ScanForObjectGoal> (roslisp-msg-protocol:ros-message)
  ((object_name
    :reader object_name
    :initarg :object_name
    :type cl:string
    :initform "")
   (target_location
    :reader target_location
    :initarg :target_location
    :type geometry_msgs-msg:Point
    :initform (cl:make-instance 'geometry_msgs-msg:Point)))
)

(cl:defclass ScanForObjectGoal (<ScanForObjectGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ScanForObjectGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ScanForObjectGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name arm_behavior_actions-msg:<ScanForObjectGoal> is deprecated: use arm_behavior_actions-msg:ScanForObjectGoal instead.")))

(cl:ensure-generic-function 'object_name-val :lambda-list '(m))
(cl:defmethod object_name-val ((m <ScanForObjectGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader arm_behavior_actions-msg:object_name-val is deprecated.  Use arm_behavior_actions-msg:object_name instead.")
  (object_name m))

(cl:ensure-generic-function 'target_location-val :lambda-list '(m))
(cl:defmethod target_location-val ((m <ScanForObjectGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader arm_behavior_actions-msg:target_location-val is deprecated.  Use arm_behavior_actions-msg:target_location instead.")
  (target_location m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ScanForObjectGoal>) ostream)
  "Serializes a message object of type '<ScanForObjectGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'object_name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'object_name))
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'target_location) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ScanForObjectGoal>) istream)
  "Deserializes a message object of type '<ScanForObjectGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'object_name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'object_name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'target_location) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ScanForObjectGoal>)))
  "Returns string type for a message object of type '<ScanForObjectGoal>"
  "arm_behavior_actions/ScanForObjectGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ScanForObjectGoal)))
  "Returns string type for a message object of type 'ScanForObjectGoal"
  "arm_behavior_actions/ScanForObjectGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ScanForObjectGoal>)))
  "Returns md5sum for a message object of type '<ScanForObjectGoal>"
  "594767e2b34d29949f18a5ea9fbef05e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ScanForObjectGoal)))
  "Returns md5sum for a message object of type 'ScanForObjectGoal"
  "594767e2b34d29949f18a5ea9fbef05e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ScanForObjectGoal>)))
  "Returns full string definition for message of type '<ScanForObjectGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%string object_name~%geometry_msgs/Point target_location~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ScanForObjectGoal)))
  "Returns full string definition for message of type 'ScanForObjectGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%string object_name~%geometry_msgs/Point target_location~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ScanForObjectGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'object_name))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'target_location))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ScanForObjectGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ScanForObjectGoal
    (cl:cons ':object_name (object_name msg))
    (cl:cons ':target_location (target_location msg))
))
