; Auto-generated. Do not edit!


(cl:in-package arm_behavior_actions-msg)


;//! \htmlinclude ScanForObjectFeedback.msg.html

(cl:defclass <ScanForObjectFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ScanForObjectFeedback (<ScanForObjectFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ScanForObjectFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ScanForObjectFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name arm_behavior_actions-msg:<ScanForObjectFeedback> is deprecated: use arm_behavior_actions-msg:ScanForObjectFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ScanForObjectFeedback>) ostream)
  "Serializes a message object of type '<ScanForObjectFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ScanForObjectFeedback>) istream)
  "Deserializes a message object of type '<ScanForObjectFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ScanForObjectFeedback>)))
  "Returns string type for a message object of type '<ScanForObjectFeedback>"
  "arm_behavior_actions/ScanForObjectFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ScanForObjectFeedback)))
  "Returns string type for a message object of type 'ScanForObjectFeedback"
  "arm_behavior_actions/ScanForObjectFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ScanForObjectFeedback>)))
  "Returns md5sum for a message object of type '<ScanForObjectFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ScanForObjectFeedback)))
  "Returns md5sum for a message object of type 'ScanForObjectFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ScanForObjectFeedback>)))
  "Returns full string definition for message of type '<ScanForObjectFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ScanForObjectFeedback)))
  "Returns full string definition for message of type 'ScanForObjectFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ScanForObjectFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ScanForObjectFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ScanForObjectFeedback
))
