/* Auto-generated by genmsg_cpp for file /home/test_user/usc-arm-calibration/arm_behavior_actions/msg/LookAtFeedback.msg */
#ifndef ARM_BEHAVIOR_ACTIONS_MESSAGE_LOOKATFEEDBACK_H
#define ARM_BEHAVIOR_ACTIONS_MESSAGE_LOOKATFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace arm_behavior_actions
{
template <class ContainerAllocator>
struct LookAtFeedback_ {
  typedef LookAtFeedback_<ContainerAllocator> Type;

  LookAtFeedback_()
  {
  }

  LookAtFeedback_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::arm_behavior_actions::LookAtFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_behavior_actions::LookAtFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct LookAtFeedback
typedef  ::arm_behavior_actions::LookAtFeedback_<std::allocator<void> > LookAtFeedback;

typedef boost::shared_ptr< ::arm_behavior_actions::LookAtFeedback> LookAtFeedbackPtr;
typedef boost::shared_ptr< ::arm_behavior_actions::LookAtFeedback const> LookAtFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arm_behavior_actions::LookAtFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arm_behavior_actions::LookAtFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arm_behavior_actions

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::arm_behavior_actions::LookAtFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::arm_behavior_actions::LookAtFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::arm_behavior_actions::LookAtFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::arm_behavior_actions::LookAtFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_behavior_actions::LookAtFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arm_behavior_actions/LookAtFeedback";
  }

  static const char* value(const  ::arm_behavior_actions::LookAtFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arm_behavior_actions::LookAtFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define a feedback message\n\
\n\
\n\
";
  }

  static const char* value(const  ::arm_behavior_actions::LookAtFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::arm_behavior_actions::LookAtFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arm_behavior_actions::LookAtFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LookAtFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_behavior_actions::LookAtFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arm_behavior_actions::LookAtFeedback_<ContainerAllocator> & v) 
  {
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARM_BEHAVIOR_ACTIONS_MESSAGE_LOOKATFEEDBACK_H

