/* Auto-generated by genmsg_cpp for file /home/jbinney/ws/arm/stacks/usc-arm-calibration/arm_behavior_actions/msg/MoveArmResult.msg */
#ifndef ARM_BEHAVIOR_ACTIONS_MESSAGE_MOVEARMRESULT_H
#define ARM_BEHAVIOR_ACTIONS_MESSAGE_MOVEARMRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace arm_behavior_actions
{
template <class ContainerAllocator>
struct MoveArmResult_ {
  typedef MoveArmResult_<ContainerAllocator> Type;

  MoveArmResult_()
  : result(0)
  , info()
  {
  }

  MoveArmResult_(const ContainerAllocator& _alloc)
  : result(0)
  , info(_alloc)
  {
  }

  typedef int32_t _result_type;
  int32_t result;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _info_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  info;

  enum { SUCCEEDED = 1 };
  enum { FAILED = 2 };

  typedef boost::shared_ptr< ::arm_behavior_actions::MoveArmResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_behavior_actions::MoveArmResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MoveArmResult
typedef  ::arm_behavior_actions::MoveArmResult_<std::allocator<void> > MoveArmResult;

typedef boost::shared_ptr< ::arm_behavior_actions::MoveArmResult> MoveArmResultPtr;
typedef boost::shared_ptr< ::arm_behavior_actions::MoveArmResult const> MoveArmResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arm_behavior_actions::MoveArmResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arm_behavior_actions::MoveArmResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arm_behavior_actions

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::arm_behavior_actions::MoveArmResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::arm_behavior_actions::MoveArmResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::arm_behavior_actions::MoveArmResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "57fa8040e7543a1ba42201128c46f31f";
  }

  static const char* value(const  ::arm_behavior_actions::MoveArmResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x57fa8040e7543a1bULL;
  static const uint64_t static_value2 = 0xa42201128c46f31fULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_behavior_actions::MoveArmResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arm_behavior_actions/MoveArmResult";
  }

  static const char* value(const  ::arm_behavior_actions::MoveArmResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arm_behavior_actions::MoveArmResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
int32 result\n\
int32 SUCCEEDED=1\n\
int32 FAILED=2\n\
string info\n\
\n\
";
  }

  static const char* value(const  ::arm_behavior_actions::MoveArmResult_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arm_behavior_actions::MoveArmResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
    stream.next(m.info);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MoveArmResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_behavior_actions::MoveArmResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arm_behavior_actions::MoveArmResult_<ContainerAllocator> & v) 
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
    s << indent << "info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.info);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARM_BEHAVIOR_ACTIONS_MESSAGE_MOVEARMRESULT_H

