/* Auto-generated by genmsg_cpp for file /home/test_user/usc-arm-calibration/arm_behavior_actions/msg/MoveArmFeedback.msg */
#ifndef ARM_BEHAVIOR_ACTIONS_MESSAGE_MOVEARMFEEDBACK_H
#define ARM_BEHAVIOR_ACTIONS_MESSAGE_MOVEARMFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace arm_behavior_actions
{
template <class ContainerAllocator>
struct MoveArmFeedback_ {
  typedef MoveArmFeedback_<ContainerAllocator> Type;

  MoveArmFeedback_()
  : progress(0.0)
  {
  }

  MoveArmFeedback_(const ContainerAllocator& _alloc)
  : progress(0.0)
  {
  }

  typedef float _progress_type;
  float progress;


  typedef boost::shared_ptr< ::arm_behavior_actions::MoveArmFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_behavior_actions::MoveArmFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MoveArmFeedback
typedef  ::arm_behavior_actions::MoveArmFeedback_<std::allocator<void> > MoveArmFeedback;

typedef boost::shared_ptr< ::arm_behavior_actions::MoveArmFeedback> MoveArmFeedbackPtr;
typedef boost::shared_ptr< ::arm_behavior_actions::MoveArmFeedback const> MoveArmFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arm_behavior_actions::MoveArmFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arm_behavior_actions::MoveArmFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arm_behavior_actions

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::arm_behavior_actions::MoveArmFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::arm_behavior_actions::MoveArmFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::arm_behavior_actions::MoveArmFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "70805092fd20e110765c7b79e8efb737";
  }

  static const char* value(const  ::arm_behavior_actions::MoveArmFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x70805092fd20e110ULL;
  static const uint64_t static_value2 = 0x765c7b79e8efb737ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_behavior_actions::MoveArmFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arm_behavior_actions/MoveArmFeedback";
  }

  static const char* value(const  ::arm_behavior_actions::MoveArmFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arm_behavior_actions::MoveArmFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define a feedback message\n\
float32 progress\n\
\n\
\n\
";
  }

  static const char* value(const  ::arm_behavior_actions::MoveArmFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::arm_behavior_actions::MoveArmFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arm_behavior_actions::MoveArmFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.progress);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MoveArmFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_behavior_actions::MoveArmFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arm_behavior_actions::MoveArmFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "progress: ";
    Printer<float>::stream(s, indent + "  ", v.progress);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARM_BEHAVIOR_ACTIONS_MESSAGE_MOVEARMFEEDBACK_H

