#!/bin/bash

ALL_PROJECTS=`rospack depends $@`
ARM_SCRIPTS_DIR=`rospack find arm_scripts`

OLD_DIR=`pwd`

for i in $ALL_PROJECTS
do
	DIR=`rospack find $i`
        echo "$i -> $DIR"
        if [ -w "$DIR" -a -e "$DIR/CMakeLists.txt" ]
        then
	  cd $DIR
	  $ARM_SCRIPTS_DIR/scripts/create_eclipse_project &
        else
          echo "Skipping $DIR"
        fi
done

cd $OLD_DIR
wait
