#!/usr/bin/env python
import sys, re
import numpy as np

fname = sys.argv[1]
f_lines  = open(fname).readlines()
print "Opened", fname


# parse the file
points = []
for line in f_lines:
    try:
        (x, y, z) = [float(s) for s in line.strip().split()][:3]
        points.append( (x, y, z) )
    except ValueError:
        continue
points = np.array(points)

# compute some stats
if len(points) == 0:
    print 'No points in file'
else:
    print "====Object stats===="
    print "number of points:", len(points)
    print "x centroid:", points[:,0].mean(axis=0)
    print "y centroid:", points[:,1].mean(axis=0)
    print "x min,max:", points[:,0].min(), points[:,0].max()
    print "y min,max:", points[:,1].min(), points[:,1].max()
    print "z min,max:", points[:,2].min(), points[:,2].max()

