(cl:defpackage arm_controller_msgs-srv
  (:use )
  (:export
   "QUERYCONTROLLERSTATUS"
   "<QUERYCONTROLLERSTATUS-REQUEST>"
   "QUERYCONTROLLERSTATUS-REQUEST"
   "<QUERYCONTROLLERSTATUS-RESPONSE>"
   "QUERYCONTROLLERSTATUS-RESPONSE"
   "SWITCHCONTROLLERSTACK"
   "<SWITCHCONTROLLERSTACK-REQUEST>"
   "SWITCHCONTROLLERSTACK-REQUEST"
   "<SWITCHCONTROLLERSTACK-RESPONSE>"
   "SWITCHCONTROLLERSTACK-RESPONSE"
  ))

