#!/usr/bin/env python
import roslib; roslib.load_manifest('arm_fiducial_cal')
import rospy
from arm_fiducial_cal import FCCorrectionNode

name = 'HeadCorrecter'
rospy.init_node(name)
node = FCCorrectionNode(name)
node.run()
