function mat = gen_mat(x_rot, y_rot, z_rot, x_trans, y_trans, z_trans)

x_rot = x_rot * pi / 180;
y_rot = y_rot * pi / 180;
z_rot = z_rot * pi / 180;

rot_mat_x = [1,          0,           0;...
             0, cos(x_rot), -sin(x_rot);...
             0, sin(x_rot), cos(x_rot)];

rot_mat_y = [cos(y_rot),  0, -sin(y_rot);...
             0,           1,           0;...
             sin(y_rot),  0, cos(y_rot)];
         
rot_mat_z = [cos(z_rot), -sin(z_rot), 0;...
             sin(z_rot),  cos(z_rot), 0;...
             0,                    0, 1];

rot = rot_mat_x * rot_mat_y * rot_mat_z;
% rot = rot_mat_z * rot_mat_y * rot_mat_x;

mat = [[rot(1,:), x_trans];...
       [rot(2,:), y_trans];...
       [rot(3,:), z_trans]];
