/* Auto-generated by genmsg_cpp for file /home/test_user/usc-arm-calibration/ccny_vision/ar_target/msg/ARMarkers3d.msg */
#ifndef AR_TARGET_MESSAGE_ARMARKERS3D_H
#define AR_TARGET_MESSAGE_ARMARKERS3D_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "ar_target/ARMarker3d.h"

namespace ar_target
{
template <class ContainerAllocator>
struct ARMarkers3d_ {
  typedef ARMarkers3d_<ContainerAllocator> Type;

  ARMarkers3d_()
  : header()
  , markers()
  {
  }

  ARMarkers3d_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , markers(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::ar_target::ARMarker3d_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ar_target::ARMarker3d_<ContainerAllocator> >::other >  _markers_type;
  std::vector< ::ar_target::ARMarker3d_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ar_target::ARMarker3d_<ContainerAllocator> >::other >  markers;


  typedef boost::shared_ptr< ::ar_target::ARMarkers3d_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ar_target::ARMarkers3d_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ARMarkers3d
typedef  ::ar_target::ARMarkers3d_<std::allocator<void> > ARMarkers3d;

typedef boost::shared_ptr< ::ar_target::ARMarkers3d> ARMarkers3dPtr;
typedef boost::shared_ptr< ::ar_target::ARMarkers3d const> ARMarkers3dConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ar_target::ARMarkers3d_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ar_target::ARMarkers3d_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ar_target

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ar_target::ARMarkers3d_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ar_target::ARMarkers3d_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ar_target::ARMarkers3d_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e16e62abb0a52ea701e6449bd556c5d0";
  }

  static const char* value(const  ::ar_target::ARMarkers3d_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe16e62abb0a52ea7ULL;
  static const uint64_t static_value2 = 0x01e6449bd556c5d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::ar_target::ARMarkers3d_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ar_target/ARMarkers3d";
  }

  static const char* value(const  ::ar_target::ARMarkers3d_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ar_target::ARMarkers3d_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
ar_target/ARMarker3d[] markers\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: ar_target/ARMarker3d\n\
int32 id\n\
float64 confidence\n\
float64[] left_u_corners\n\
float64[] left_v_corners\n\
float64[] right_u_corners\n\
float64[] right_v_corners\n\
geometry_msgs/Point[] corner_positions\n\
geometry_msgs/Quaternion[] corner_orientations\n\
geometry_msgs/Pose center_pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
";
  }

  static const char* value(const  ::ar_target::ARMarkers3d_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::ar_target::ARMarkers3d_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::ar_target::ARMarkers3d_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ar_target::ARMarkers3d_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.markers);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ARMarkers3d_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ar_target::ARMarkers3d_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ar_target::ARMarkers3d_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "markers[]" << std::endl;
    for (size_t i = 0; i < v.markers.size(); ++i)
    {
      s << indent << "  markers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ar_target::ARMarker3d_<ContainerAllocator> >::stream(s, indent + "    ", v.markers[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // AR_TARGET_MESSAGE_ARMARKERS3D_H

