/* Auto-generated by genmsg_cpp for file /home/jbinney/ws/arm/stacks/usc-arm-calibration/ccny_vision/ar_target/msg/ARMarkers.msg */
#ifndef AR_TARGET_MESSAGE_ARMARKERS_H
#define AR_TARGET_MESSAGE_ARMARKERS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "ar_target/ARMarker.h"

namespace ar_target
{
template <class ContainerAllocator>
struct ARMarkers_ {
  typedef ARMarkers_<ContainerAllocator> Type;

  ARMarkers_()
  : header()
  , markers()
  {
  }

  ARMarkers_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , markers(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::ar_target::ARMarker_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ar_target::ARMarker_<ContainerAllocator> >::other >  _markers_type;
  std::vector< ::ar_target::ARMarker_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ar_target::ARMarker_<ContainerAllocator> >::other >  markers;


  typedef boost::shared_ptr< ::ar_target::ARMarkers_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ar_target::ARMarkers_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ARMarkers
typedef  ::ar_target::ARMarkers_<std::allocator<void> > ARMarkers;

typedef boost::shared_ptr< ::ar_target::ARMarkers> ARMarkersPtr;
typedef boost::shared_ptr< ::ar_target::ARMarkers const> ARMarkersConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ar_target::ARMarkers_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ar_target::ARMarkers_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ar_target

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ar_target::ARMarkers_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ar_target::ARMarkers_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ar_target::ARMarkers_<ContainerAllocator> > {
  static const char* value() 
  {
    return "39a7f2e5f0eae4c86572d1aac1378022";
  }

  static const char* value(const  ::ar_target::ARMarkers_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x39a7f2e5f0eae4c8ULL;
  static const uint64_t static_value2 = 0x6572d1aac1378022ULL;
};

template<class ContainerAllocator>
struct DataType< ::ar_target::ARMarkers_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ar_target/ARMarkers";
  }

  static const char* value(const  ::ar_target::ARMarkers_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ar_target::ARMarkers_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
ARMarker[] markers\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: ar_target/ARMarker\n\
int32 id\n\
float64 confidence\n\
geometry_msgs/Quaternion quaternion\n\
float64[] u_corners\n\
float64[] v_corners\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::ar_target::ARMarkers_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::ar_target::ARMarkers_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::ar_target::ARMarkers_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ar_target::ARMarkers_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.markers);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ARMarkers_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ar_target::ARMarkers_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ar_target::ARMarkers_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "markers[]" << std::endl;
    for (size_t i = 0; i < v.markers.size(); ++i)
    {
      s << indent << "  markers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ar_target::ARMarker_<ContainerAllocator> >::stream(s, indent + "    ", v.markers[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // AR_TARGET_MESSAGE_ARMARKERS_H

