#!/usr/bin/env python
import roslib; roslib.load_manifest('arm_sensor_monitor')
import time
import rospy
from sensor_msgs.msg import Image
from arm_dashboard_client import DashboardClient

def msg_callback(msg):
    global last_t
    last_t = time.time()

rospy.init_node('HoneybeeMonitor')
rospy.sleep(5.0)

last_t = time.time()
sub = rospy.Subscriber('/Honeybee/left/image_color_rect', Image, msg_callback)
dc = DashboardClient()

while not rospy.is_shutdown():
    rospy.sleep(1.0)
    rospy.logdebug('delta t: %f' % (time.time() - last_t,))
    if time.time() - last_t > 2.0:
        dc.error('Bumblebee node is not publishing images! Firewire problems? Maybe restart everything.')
        rospy.logerr('Bumblebee node is not publishing images! Firewire problems? Maybe restart everything.')

