/* Auto-generated by genmsg_cpp for file /home/jbinney/ws/arm/stacks/usc-arm-calibration/arm_controller_msgs/msg/Acceleration.msg */
#ifndef ARM_CONTROLLER_MSGS_MESSAGE_ACCELERATION_H
#define ARM_CONTROLLER_MSGS_MESSAGE_ACCELERATION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace arm_controller_msgs
{
template <class ContainerAllocator>
struct Acceleration_ {
  typedef Acceleration_<ContainerAllocator> Type;

  Acceleration_()
  : header()
  , acceleration()
  {
    acceleration.assign(0.0);
  }

  Acceleration_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , acceleration()
  {
    acceleration.assign(0.0);
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef boost::array<double, 3>  _acceleration_type;
  boost::array<double, 3>  acceleration;

  enum { ACC_X = 0 };
  enum { ACC_Y = 1 };
  enum { ACC_Z = 2 };

  typedef boost::shared_ptr< ::arm_controller_msgs::Acceleration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_controller_msgs::Acceleration_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Acceleration
typedef  ::arm_controller_msgs::Acceleration_<std::allocator<void> > Acceleration;

typedef boost::shared_ptr< ::arm_controller_msgs::Acceleration> AccelerationPtr;
typedef boost::shared_ptr< ::arm_controller_msgs::Acceleration const> AccelerationConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arm_controller_msgs::Acceleration_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arm_controller_msgs::Acceleration_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arm_controller_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::arm_controller_msgs::Acceleration_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::arm_controller_msgs::Acceleration_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::arm_controller_msgs::Acceleration_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ee6895ce67b7feb67d4d61b2d2654d26";
  }

  static const char* value(const  ::arm_controller_msgs::Acceleration_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xee6895ce67b7feb6ULL;
  static const uint64_t static_value2 = 0x7d4d61b2d2654d26ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_controller_msgs::Acceleration_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arm_controller_msgs/Acceleration";
  }

  static const char* value(const  ::arm_controller_msgs::Acceleration_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arm_controller_msgs::Acceleration_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Standard ROS header\n\
Header header\n\
\n\
# Acceleration values in ACC_X, ACC_Y, ACC_Z, in m/s^2\n\
float64[3] acceleration\n\
\n\
# constants for indexing into the above array\n\
int32 ACC_X=0\n\
int32 ACC_Y=1\n\
int32 ACC_Z=2\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::arm_controller_msgs::Acceleration_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::arm_controller_msgs::Acceleration_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::arm_controller_msgs::Acceleration_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arm_controller_msgs::Acceleration_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.acceleration);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Acceleration_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_controller_msgs::Acceleration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arm_controller_msgs::Acceleration_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "acceleration[]" << std::endl;
    for (size_t i = 0; i < v.acceleration.size(); ++i)
    {
      s << indent << "  acceleration[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.acceleration[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROLLER_MSGS_MESSAGE_ACCELERATION_H

