/* Auto-generated by genmsg_cpp for file /home/test_user/usc-arm-calibration/arm_controller_msgs/msg/GraspStatus.msg */
#ifndef ARM_CONTROLLER_MSGS_MESSAGE_GRASPSTATUS_H
#define ARM_CONTROLLER_MSGS_MESSAGE_GRASPSTATUS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace arm_controller_msgs
{
template <class ContainerAllocator>
struct GraspStatus_ {
  typedef GraspStatus_<ContainerAllocator> Type;

  GraspStatus_()
  : status(0)
  {
  }

  GraspStatus_(const ContainerAllocator& _alloc)
  : status(0)
  {
  }

  typedef int32_t _status_type;
  int32_t status;

  enum { GRASP_SUCCEEDED = 1 };
  enum { GRASP_FAILED = 2 };
  enum { RELEASE_SUCCEEDED = 3 };
  enum { RELEASE_FAILED = 4 };
  enum { HOLDING_FAILED = 5 };

  typedef boost::shared_ptr< ::arm_controller_msgs::GraspStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_controller_msgs::GraspStatus_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GraspStatus
typedef  ::arm_controller_msgs::GraspStatus_<std::allocator<void> > GraspStatus;

typedef boost::shared_ptr< ::arm_controller_msgs::GraspStatus> GraspStatusPtr;
typedef boost::shared_ptr< ::arm_controller_msgs::GraspStatus const> GraspStatusConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arm_controller_msgs::GraspStatus_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arm_controller_msgs::GraspStatus_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arm_controller_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::arm_controller_msgs::GraspStatus_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::arm_controller_msgs::GraspStatus_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::arm_controller_msgs::GraspStatus_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6c6016937bbcb3fca485c1a9ec5b1493";
  }

  static const char* value(const  ::arm_controller_msgs::GraspStatus_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6c6016937bbcb3fcULL;
  static const uint64_t static_value2 = 0xa485c1a9ec5b1493ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_controller_msgs::GraspStatus_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arm_controller_msgs/GraspStatus";
  }

  static const char* value(const  ::arm_controller_msgs::GraspStatus_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arm_controller_msgs::GraspStatus_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Status\n\
int32 status\n\
\n\
# Possible types of status\n\
int32 GRASP_SUCCEEDED=1\n\
int32 GRASP_FAILED=2\n\
int32 RELEASE_SUCCEEDED=3\n\
int32 RELEASE_FAILED=4\n\
int32 HOLDING_FAILED=5\n\
";
  }

  static const char* value(const  ::arm_controller_msgs::GraspStatus_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::arm_controller_msgs::GraspStatus_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arm_controller_msgs::GraspStatus_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.status);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GraspStatus_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_controller_msgs::GraspStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arm_controller_msgs::GraspStatus_<ContainerAllocator> & v) 
  {
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROLLER_MSGS_MESSAGE_GRASPSTATUS_H

