/* Auto-generated by genmsg_cpp for file /home/jbinney/ws/arm/stacks/usc-arm-calibration/arm_controller_msgs/msg/IncreaseMaxFingerTorque.msg */
#ifndef ARM_CONTROLLER_MSGS_MESSAGE_INCREASEMAXFINGERTORQUE_H
#define ARM_CONTROLLER_MSGS_MESSAGE_INCREASEMAXFINGERTORQUE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace arm_controller_msgs
{
template <class ContainerAllocator>
struct IncreaseMaxFingerTorque_ {
  typedef IncreaseMaxFingerTorque_<ContainerAllocator> Type;

  IncreaseMaxFingerTorque_()
  : num_steps(0)
  {
  }

  IncreaseMaxFingerTorque_(const ContainerAllocator& _alloc)
  : num_steps(0)
  {
  }

  typedef int32_t _num_steps_type;
  int32_t num_steps;


  typedef boost::shared_ptr< ::arm_controller_msgs::IncreaseMaxFingerTorque_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_controller_msgs::IncreaseMaxFingerTorque_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct IncreaseMaxFingerTorque
typedef  ::arm_controller_msgs::IncreaseMaxFingerTorque_<std::allocator<void> > IncreaseMaxFingerTorque;

typedef boost::shared_ptr< ::arm_controller_msgs::IncreaseMaxFingerTorque> IncreaseMaxFingerTorquePtr;
typedef boost::shared_ptr< ::arm_controller_msgs::IncreaseMaxFingerTorque const> IncreaseMaxFingerTorqueConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arm_controller_msgs::IncreaseMaxFingerTorque_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arm_controller_msgs::IncreaseMaxFingerTorque_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arm_controller_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::arm_controller_msgs::IncreaseMaxFingerTorque_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::arm_controller_msgs::IncreaseMaxFingerTorque_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::arm_controller_msgs::IncreaseMaxFingerTorque_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ec92edc7544f0f2ee877e76a11710806";
  }

  static const char* value(const  ::arm_controller_msgs::IncreaseMaxFingerTorque_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xec92edc7544f0f2eULL;
  static const uint64_t static_value2 = 0xe877e76a11710806ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_controller_msgs::IncreaseMaxFingerTorque_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arm_controller_msgs/IncreaseMaxFingerTorque";
  }

  static const char* value(const  ::arm_controller_msgs::IncreaseMaxFingerTorque_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arm_controller_msgs::IncreaseMaxFingerTorque_<ContainerAllocator> > {
  static const char* value() 
  {
    return "##message requesting for a MT increase of the fingers\n\
int32 num_steps ##100 will have a duration 0f 300ms\n\
\n\
\n\
";
  }

  static const char* value(const  ::arm_controller_msgs::IncreaseMaxFingerTorque_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::arm_controller_msgs::IncreaseMaxFingerTorque_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arm_controller_msgs::IncreaseMaxFingerTorque_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.num_steps);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct IncreaseMaxFingerTorque_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_controller_msgs::IncreaseMaxFingerTorque_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arm_controller_msgs::IncreaseMaxFingerTorque_<ContainerAllocator> & v) 
  {
    s << indent << "num_steps: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_steps);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROLLER_MSGS_MESSAGE_INCREASEMAXFINGERTORQUE_H

