/* Auto-generated by genmsg_cpp for file /home/test_user/usc-arm-calibration/arm_controller_msgs/msg/UpdateStrainGagesCalibration.msg */
#ifndef ARM_CONTROLLER_MSGS_MESSAGE_UPDATESTRAINGAGESCALIBRATION_H
#define ARM_CONTROLLER_MSGS_MESSAGE_UPDATESTRAINGAGESCALIBRATION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace arm_controller_msgs
{
template <class ContainerAllocator>
struct UpdateStrainGagesCalibration_ {
  typedef UpdateStrainGagesCalibration_<ContainerAllocator> Type;

  UpdateStrainGagesCalibration_()
  : offsets()
  , slopes()
  {
    offsets.assign(0.0);
    slopes.assign(0.0);
  }

  UpdateStrainGagesCalibration_(const ContainerAllocator& _alloc)
  : offsets()
  , slopes()
  {
    offsets.assign(0.0);
    slopes.assign(0.0);
  }

  typedef boost::array<double, 3>  _offsets_type;
  boost::array<double, 3>  offsets;

  typedef boost::array<double, 3>  _slopes_type;
  boost::array<double, 3>  slopes;


  typedef boost::shared_ptr< ::arm_controller_msgs::UpdateStrainGagesCalibration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_controller_msgs::UpdateStrainGagesCalibration_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct UpdateStrainGagesCalibration
typedef  ::arm_controller_msgs::UpdateStrainGagesCalibration_<std::allocator<void> > UpdateStrainGagesCalibration;

typedef boost::shared_ptr< ::arm_controller_msgs::UpdateStrainGagesCalibration> UpdateStrainGagesCalibrationPtr;
typedef boost::shared_ptr< ::arm_controller_msgs::UpdateStrainGagesCalibration const> UpdateStrainGagesCalibrationConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arm_controller_msgs::UpdateStrainGagesCalibration_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arm_controller_msgs::UpdateStrainGagesCalibration_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arm_controller_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::arm_controller_msgs::UpdateStrainGagesCalibration_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::arm_controller_msgs::UpdateStrainGagesCalibration_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::arm_controller_msgs::UpdateStrainGagesCalibration_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9ea971c21839a0c80c442ca4d7d78661";
  }

  static const char* value(const  ::arm_controller_msgs::UpdateStrainGagesCalibration_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9ea971c21839a0c8ULL;
  static const uint64_t static_value2 = 0x0c442ca4d7d78661ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_controller_msgs::UpdateStrainGagesCalibration_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arm_controller_msgs/UpdateStrainGagesCalibration";
  }

  static const char* value(const  ::arm_controller_msgs::UpdateStrainGagesCalibration_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arm_controller_msgs::UpdateStrainGagesCalibration_<ContainerAllocator> > {
  static const char* value() 
  {
    return "##message containing the new strain gages calibration infos\n\
\n\
#each an array of 24 touch values\n\
float64[3] offsets\n\
float64[3] slopes\n\
\n\
\n\
";
  }

  static const char* value(const  ::arm_controller_msgs::UpdateStrainGagesCalibration_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::arm_controller_msgs::UpdateStrainGagesCalibration_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arm_controller_msgs::UpdateStrainGagesCalibration_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.offsets);
    stream.next(m.slopes);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct UpdateStrainGagesCalibration_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_controller_msgs::UpdateStrainGagesCalibration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arm_controller_msgs::UpdateStrainGagesCalibration_<ContainerAllocator> & v) 
  {
    s << indent << "offsets[]" << std::endl;
    for (size_t i = 0; i < v.offsets.size(); ++i)
    {
      s << indent << "  offsets[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.offsets[i]);
    }
    s << indent << "slopes[]" << std::endl;
    for (size_t i = 0; i < v.slopes.size(); ++i)
    {
      s << indent << "  slopes[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.slopes[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROLLER_MSGS_MESSAGE_UPDATESTRAINGAGESCALIBRATION_H

