(cl:in-package arm_calibrate_extrinsics-msg)
(cl:export '(HEADER-VAL
          HEADER
          IDS-VAL
          IDS
          U_CORNER_1-VAL
          U_CORNER_1
          V_CORNER_1-VAL
          V_CORNER_1
          U_CORNER_2-VAL
          U_CORNER_2
          V_CORNER_2-VAL
          V_CORNER_2
          U_CORNER_3-VAL
          U_CORNER_3
          V_CORNER_3-VAL
          V_CORNER_3
          U_CORNER_4-VAL
          U_CORNER_4
          V_CORNER_4-VAL
          V_CORNER_4
          POINTS-VAL
          POINTS
          IMAGE-VAL
          IMAGE
          CAMERA_INFO-VAL
          CAMERA_INFO
          HEAD_TRANSFORM_BASE-VAL
          HEAD_TRANSFORM_BASE
          CAM_TRANSFORM_HEAD-VAL
          CAM_TRANSFORM_HEAD
))