#!/usr/bin/env python
import time
import roslib
roslib.load_manifest('pier')
import pier_ext

pier_ext.init('PierTestNode')
node_handle = pier_ext.NodeHandle()
while pier_ext.ok():
    msg = pier_ext.String()
    msg.data = 'string data'
    pier_ext.ros_info('Message data: %s' % msg.data)
    pier_ext.spinOnce()
    print 'looping'
    pier_ext.ros_info('Looping...')
    time.sleep(1.0)
    
pier_ext.ros_info('Exiting')
