/* Auto-generated by genmsg_cpp for file /home/test_user/usc-arm-calibration/arm_head_control/msg/LookAtActionGoal.msg */
#ifndef ARM_HEAD_CONTROL_MESSAGE_LOOKATACTIONGOAL_H
#define ARM_HEAD_CONTROL_MESSAGE_LOOKATACTIONGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "actionlib_msgs/GoalID.h"
#include "arm_head_control/LookAtGoal.h"

namespace arm_head_control
{
template <class ContainerAllocator>
struct LookAtActionGoal_ {
  typedef LookAtActionGoal_<ContainerAllocator> Type;

  LookAtActionGoal_()
  : header()
  , goal_id()
  , goal()
  {
  }

  LookAtActionGoal_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , goal_id(_alloc)
  , goal(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
   ::actionlib_msgs::GoalID_<ContainerAllocator>  goal_id;

  typedef  ::arm_head_control::LookAtGoal_<ContainerAllocator>  _goal_type;
   ::arm_head_control::LookAtGoal_<ContainerAllocator>  goal;


  typedef boost::shared_ptr< ::arm_head_control::LookAtActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_head_control::LookAtActionGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct LookAtActionGoal
typedef  ::arm_head_control::LookAtActionGoal_<std::allocator<void> > LookAtActionGoal;

typedef boost::shared_ptr< ::arm_head_control::LookAtActionGoal> LookAtActionGoalPtr;
typedef boost::shared_ptr< ::arm_head_control::LookAtActionGoal const> LookAtActionGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::arm_head_control::LookAtActionGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::arm_head_control::LookAtActionGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace arm_head_control

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::arm_head_control::LookAtActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::arm_head_control::LookAtActionGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::arm_head_control::LookAtActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "97d548585f010eb1b580140071ef72ef";
  }

  static const char* value(const  ::arm_head_control::LookAtActionGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x97d548585f010eb1ULL;
  static const uint64_t static_value2 = 0xb580140071ef72efULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_head_control::LookAtActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "arm_head_control/LookAtActionGoal";
  }

  static const char* value(const  ::arm_head_control::LookAtActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::arm_head_control::LookAtActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
LookAtGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: arm_head_control/LookAtGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
float64[4] ptu_joint_angels\n\
\n\
";
  }

  static const char* value(const  ::arm_head_control::LookAtActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::arm_head_control::LookAtActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::arm_head_control::LookAtActionGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::arm_head_control::LookAtActionGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.goal_id);
    stream.next(m.goal);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LookAtActionGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_head_control::LookAtActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::arm_head_control::LookAtActionGoal_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
s << std::endl;
    Printer< ::arm_head_control::LookAtGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARM_HEAD_CONTROL_MESSAGE_LOOKATACTIONGOAL_H

