(cl:defpackage arm_head_control-msg
  (:use )
  (:export
   "<LOOKATGOAL>"
   "LOOKATGOAL"
   "<LOOKATACTIONRESULT>"
   "LOOKATACTIONRESULT"
   "<LOOKATACTION>"
   "LOOKATACTION"
   "<LOOKATACTIONGOAL>"
   "LOOKATACTIONGOAL"
   "<LOOKATRESULT>"
   "LOOKATRESULT"
   "<LOOKATFEEDBACK>"
   "LOOKATFEEDBACK"
   "<LOOKATACTIONFEEDBACK>"
   "LOOKATACTIONFEEDBACK"
  ))

