; Auto-generated. Do not edit!


(cl:in-package arm_head_control-msg)


;//! \htmlinclude LookAtFeedback.msg.html

(cl:defclass <LookAtFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass LookAtFeedback (<LookAtFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LookAtFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LookAtFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name arm_head_control-msg:<LookAtFeedback> is deprecated: use arm_head_control-msg:LookAtFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LookAtFeedback>) ostream)
  "Serializes a message object of type '<LookAtFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LookAtFeedback>) istream)
  "Deserializes a message object of type '<LookAtFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LookAtFeedback>)))
  "Returns string type for a message object of type '<LookAtFeedback>"
  "arm_head_control/LookAtFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LookAtFeedback)))
  "Returns string type for a message object of type 'LookAtFeedback"
  "arm_head_control/LookAtFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LookAtFeedback>)))
  "Returns md5sum for a message object of type '<LookAtFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LookAtFeedback)))
  "Returns md5sum for a message object of type 'LookAtFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LookAtFeedback>)))
  "Returns full string definition for message of type '<LookAtFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LookAtFeedback)))
  "Returns full string definition for message of type 'LookAtFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LookAtFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LookAtFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LookAtFeedback
))
