(cl:defpackage arm_msgs-srv
  (:use )
  (:export
   "GETTABLECOEFFS"
   "<GETTABLECOEFFS-REQUEST>"
   "GETTABLECOEFFS-REQUEST"
   "<GETTABLECOEFFS-RESPONSE>"
   "GETTABLECOEFFS-RESPONSE"
   "FINDOBJECTMULTI"
   "<FINDOBJECTMULTI-REQUEST>"
   "FINDOBJECTMULTI-REQUEST"
   "<FINDOBJECTMULTI-RESPONSE>"
   "FINDOBJECTMULTI-RESPONSE"
   "FINDOBJECT"
   "<FINDOBJECT-REQUEST>"
   "FINDOBJECT-REQUEST"
   "<FINDOBJECT-RESPONSE>"
   "FINDOBJECT-RESPONSE"
  ))

